package com.maaitlunghau.__mvc_thymeleaf.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "users")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true, length = 50)
    private String username;

    @Column(nullable = false, unique = true, length = 100)
    private String email;

    // Lưu password đã được hash — không bao giờ lưu plain text.
    // length = 60 vừa đủ cho BCrypt hash (luôn ra đúng 60 ký tự).
    // (Store BCrypt hash only — never plain text; BCrypt always produces 60-char output)
    @Column(nullable = false, length = 60)
    private String password;

    @Column(nullable = false)
    private int age;

    protected User() {}

    public User(String username, String email, String password, int age) {
        this.username = username;
        this.email = email;
        this.password = password;
        this.age = age;
    }

    public Long getId() { return id; }
    public String getUsername() { return username; }
    public String getEmail() { return email; }
    public String getPassword() { return password; }
    public int getAge() { return age; }

    // Không có setId() — ID do DB generate, không được set từ ngoài.
    // (No setId(): auto-generated by DB, must never be mutated externally)
    public void setUsername(String username) { this.username = username; }
    public void setEmail(String email) { this.email = email; }
    public void setPassword(String password) { this.password = password; }
    public void setAge(int age) { this.age = age; }

    // equals/hashCode chỉ dựa trên id — tránh vấn đề với Hibernate proxy và hashCode mutation.
    // (id-only equals/hashCode: safe with Hibernate proxies and pre/post-persist state)
    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (!(obj instanceof User other)) return false;
        return id != null && id.equals(other.id);
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }

    @Override
    public String toString() {
        return "User [id=" + id + ", username=" + username + ", email=" + email + ", age=" + age + "]";
    }
}
